win count mathematically generating
aydin41k/catematics pull request #10
Opened 2023-12-31 09:59 UTC by Sabbirfeni

Win count mathematically generating now.

5 wins --> Wins: 5
10 wins: Wins: 10
12 wins: Wins: 10 + 2
20 wins: Wins: 10 x 2
25 wins: Wins: 10 x 2 + 5

2023-12-31 11:05 UTC, aydin41k requested changes

2023-12-31 11:05 UTC, aydin41k commented on script.js
> +      const roundNumber = Number(wins.toString().slice(0, 1))
Try 100 wins, and this will output '10 x 1 + 90', which is incorrect (should be 10 x 10).
Use this formula: Math.round(Math.floor(wins / 10))

2023-12-31 11:05 UTC, aydin41k commented on script.js
> +      const extraNumber = wins - (10 * roundNumber)
Easier to use the remainder operand: `wins % 10`

2023-12-31 13:35 UTC, Sabbirfeni commented
Thanks for the instructions. I will get down to change those things once I get to work.

2024-01-01 09:49 UTC, Sabbirfeni commented
Hey I have made the changes. Please checkout.

2024-01-03 06:13 UTC, Sabbirfeni commented
Hey, have you checked the changes?

2024-01-03 09:06 UTC, aydin41k approved these changes

2024-01-03 09:06 UTC, merged

2024-01-03 09:07 UTC, aydin41k commented
@Sabbirfeni Merged, thanks a lot!

2024-01-03 09:15 UTC, Sabbirfeni commented
Thank you too!

2024-01-03 09:15 UTC, Sabbirfeni commented
Can we join over Linkedin?

2024-01-03 21:51 UTC, aydin41k commented
@Sabbirfeni I don't use LinkedIn, but I followed you on Github - if I ever join LinkedIn, I'll let you know ;)

2024-01-04 02:59 UTC, Sabbirfeni commented
Okay thank you. Have a good one!